// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpjoc-rUUtFWxptaWZf4Dqg45ayKlpqbs',
    appId: '1:982919755646:web:1b45ea0f471902435b652f',
    messagingSenderId: '982919755646',
    projectId: 'puntodventa-147f9',
    authDomain: 'puntodventa-147f9.firebaseapp.com',
    storageBucket: 'puntodventa-147f9.appspot.com',
    measurementId: 'G-1N80N4S3T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxGac3le8Pd6y9TKulsPDUzgzxxj-_kws',
    appId: '1:982919755646:android:4d20084a9f39c6ff5b652f',
    messagingSenderId: '982919755646',
    projectId: 'puntodventa-147f9',
    storageBucket: 'puntodventa-147f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmuVQpdgB8QOQQKDJztVN1mX3QNestqck',
    appId: '1:982919755646:ios:7a52c8b37bc1cb3c5b652f',
    messagingSenderId: '982919755646',
    projectId: 'puntodventa-147f9',
    storageBucket: 'puntodventa-147f9.appspot.com',
    iosBundleId: 'com.example.puntodventa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmuVQpdgB8QOQQKDJztVN1mX3QNestqck',
    appId: '1:982919755646:ios:7a52c8b37bc1cb3c5b652f',
    messagingSenderId: '982919755646',
    projectId: 'puntodventa-147f9',
    storageBucket: 'puntodventa-147f9.appspot.com',
    iosBundleId: 'com.example.puntodventa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpjoc-rUUtFWxptaWZf4Dqg45ayKlpqbs',
    appId: '1:982919755646:web:23197f8570bc44995b652f',
    messagingSenderId: '982919755646',
    projectId: 'puntodventa-147f9',
    authDomain: 'puntodventa-147f9.firebaseapp.com',
    storageBucket: 'puntodventa-147f9.appspot.com',
    measurementId: 'G-F6HV172MT0',
  );
}
